image:
  # -- Image pull policy.
  pullPolicy: IfNotPresent
  # -- Image repository.
  repository: registry.k8s.io/kwok/kwok
  # -- Overrides the image tag whose default is {{ .Chart.AppVersion }}.
  tag: ""

# -- Image pull secrets.
imagePullSecrets: []

# -- Override the `name` of the chart.
nameOverride: ""

# -- Override the `fullname` of the chart.
fullnameOverride: "kwok-controller"

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
resources: {}
affinity: {}

# -- The replica count for Deployment.
replicas: 1

# -- Controls whether the pod to use `hostNetwork` to avoid the issue #819 for kind clusters.
hostNetwork: false
